package:
  name: dekupl-run
  version: "1.1"

source:
  git_url: https://github.com/Transipedia/dekupl-run

build:
  number: 0
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  build:
    - boost
    - cmake
    # - kallisto =0.43.0

  run:
    - snakemake <5.0.0
    - rpy2
    - r-base
    - r-rcolorbrewer
    - r-pheatmap
    - r-foreach
    - r-doparallel
    - bioconductor-deseq2
    # - kallisto =0.43.0

about:
  home: https://github.com/Transipedia/dekupl-run
  license: MIT
  license_file: LICENSE


