variables:
  GIT_SUBMODULE_STRATEGY: recursive

docker_base:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin "$CI_REGISTRY"
  script:
    - docker pull "$CI_REGISTRY_IMAGE":base || true
    - docker build --cache-from "$CI_REGISTRY_IMAGE":base -t "$CI_REGISTRY_IMAGE":base -f Dockerfile.base .
    - docker push "$CI_REGISTRY_IMAGE":base
  only:
    changes:
      - Dockerfile.base
      - install_r_packages.R

test:
  image: registry.gitlab.com/transipedia/dekupl-run:base
  stage: test
  script:
    - cp /usr/local/bin/computeNF $CI_PROJECT_DIR/bin
    - cp /usr/local/bin/joinCounts $CI_PROJECT_DIR/bin
    - cp /usr/local/bin/mergeTags $CI_PROJECT_DIR/bin
    - cp /usr/local/bin/TtestFilter $CI_PROJECT_DIR/bin
    - cp /usr/local/bin/kallisto $CI_PROJECT_DIR/bin
    - snakemake --configfile tests/config_transcript_to_gene_mapping.json
    - snakemake --configfile tests/config_ttest.json
    - snakemake --configfile tests/config_deseq2.json
    - snakemake --configfile tests/config_limma-voom.json

delivery-conda:
  image: continuumio/miniconda3:4.5.11
  stage: deploy
  only:
    - tags
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add default_channels https://repo.anaconda.com/pkgs/pro
    - conda config --add default_channels https://repo.anaconda.com/pkgs/free
    - conda config --add default_channels https://repo.anaconda.com/pkgs/main
    - conda config --add channels conda-forge
    - conda config --add channels defaults
    - conda config --add channels bioconda
    - conda create -n build anaconda-client conda-build
    - source activate build
    - conda info -a
    - conda build --user transipedia --token $ANACONDA_TOKEN recipe

test-conda:
  image: continuumio/miniconda3:4.5.11
  stage: test-deploy
  only:
    - tags
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda config --set always_yes yes --set changeps1 no
    - conda create -n dekupl --override-channels -c transipedia -c bioconda -c conda-forge -c https://repo.anaconda.com/pkgs/main -c https://repo.anaconda.com/pkgs/free -c https://repo.anaconda.com/pkgs/pro dekupl-run
    - source activate dekupl
    - conda info -a
    - dekupl-run --configfile tests/config_transcript_to_gene_mapping.json
    - dekupl-run --configfile tests/config_ttest.json
    - dekupl-run --configfile tests/config_deseq2.json
    - dekupl-run --configfile tests/config_limma-voom.json

delivery-docker:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  only:
    - tags
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build --pull --cache-from  transipedia/dekupl-run  -t transipedia/dekupl-run -t transipedia/dekupl-run:$CI_COMMIT_REF_NAME .
    - docker push transipedia/dekupl-run

stages:
  - build
  - test
  - deploy
  - test-deploy
