sudo: required
dist: trusty
language: python
python:
  - '3.6'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-math-dev
      - pigz
      - cmake
      - r-base
      - r-base-dev
before_install:
install:
  # For Ubuntu 12.04, we have only R 2.x available and thus need an older rpy2
  # version (2.2.5). For Ubuntu 14.04, we have R 3.0.x available which works
  # with rpy2 2.3.9 (see trusty packages).
  - pip install rpy2==2.3.9
  - pip install snakemake
  # Install all R packages
  - sudo Rscript install_r_packages.R
  # Install latest jellyfish version
  - wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.9/jellyfish-2.2.9-linux-static
  - mv jellyfish-2.2.9-linux-static jellyfish
  - chmod +x jellyfish
  - export PATH=$PATH:$PWD
script: 
  - snakemake --configfile tests/config_ttest.json
