language: python
python:
  - '3.6'
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-math-dev
      - python3-rpy2
      - pigz
      - cmake
      - r-base
      - r-base-dev # Not sure if needed
before_install:
install:
  - pip install snakemake
  - sudo Rscript install_r_packages.R
  # Install latest jellyfish version
  - wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.9/jellyfish-2.2.9-linux-static
  - mv jellyfish-2.2.9-linux-static jellyfish
  - chmod +x jellyfish
  - export PATH=$PATH:$PWD
script: 
  - snakemake --configfile tests/config_ttest.json
